# config.yaml

# Setup hyperparameters
num_epochs: 5
n_critic: 25
batch_size: 512
num_workers: 0
hidden_units: 100
learning_rate: 0.0002
lambda_gp: 10
z_dim: 128
embed_dim: 4

# MIMO setting
nr: 4 # Number of receive antennas
nt: 4 # Number of transmit antennas
l: 23 # Number of paths in the multipath channel
t: 128 # Number of samples in the ip/op signal
